// <auto-generated />
namespace Education.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class onlyoneoption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onlyoneoption));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251626401_only one option"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
