// <auto-generated />
namespace Education.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changethenameofsomefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changethenameofsomefields));
        
        string IMigrationMetadata.Id
        {
            get { return "201604250259003_Change the name of some fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
